{title: GOOD GOLLY MISS MOLLY}
{subtitle: Little Richard}
{start_of_verse: Intro}
[G]     [G]     [G]     [G][,]       [C]     [C][,]       [G]     [G][,]       [D]     [C]     [G]     [|][G][|]

[NC]Good golly Miss [G]Molly, sure like to ball-oooh.
Good golly Miss [C]Molly, sure like to [G]ball.
When you're rockin' and a [D]rollin', [C]can't hear your momma [G]call. [G]

From the [|][G]ea[|]rly early mornin' till the [|][G]ea[|]rly early night
When I [|][G]ca[|]ught Miss Molly rockin' at the [|][G]ho[|]use of blue light.

[NC]Good golly Miss [C]Molly, sure like to [G]ball.
When you're rockin' and a [D]rollin', [C]can't hear your momma [G]call. [G]

[|][G]Mo[|]mma Poppa told me son you [|][G]be[|]tter watch your step,
If they [|][G]kn[|]ew about Miss Molly I'd have to [|][G]wa[|]tch my Pop myself.

[NC]Good golly Miss [C]Molly, sure like to [G]ball.
When you're rockin' and a [D]rollin', [C]can't hear your momma [G]call.  Awwwwww.

[G] [G]     [G]     [G][,]       [C]     [C][,]       [G]     [G][,]       [D]     [C]     [G]     [|][G][|]

[NC]Good golly Miss [G]Molly, sure like to ball-oooh.
Good golly Miss [C]Molly, sure like to [G]ball.
When you're rockin' and a [D]rollin', [C]can't hear your momma [G]call.[G]

I'm [|][G]go[|]ing to the corner gonna [|][G]bu[|]y a diamond ring.
When she [|][G]hu[|]gs me and kiss-me-make-me [|][G]tin[|]g-a-ling-a-ling.

[NC]Good golly Miss [C]Molly, sure like to [G]ball.
When you're rockin' and a [D]rollin', [|][C]ca[|]n't hear your momma [G]call. [-][D][-][G][-][D][-][|][G][|]
